version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: gitsweeper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.gitCommit={{.Commit}}
    binary: gitsweeper


archives:
  - name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}
    files:
      - README.md
      - LICENSE.md

checksum:
  name_template: 'checksums.txt'



changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

homebrew_casks:
  - name: gitsweeper
    conflicts:
      - formula: gitsweeper
    repository:
      owner: petems
      name: homebrew-gitsweeper
      branch: master
      # Create a Github Finegrained Access Token
      # https://github.com/settings/personal-access-tokens
      # Set the scope to just the petems/homebrew-gitsweeper repo, with pull-request write permissions
      # Open https://github.com/petems/gitsweeper/settings/secrets/actions
      # Create a new secret called HOMEBREW_TOKEN with the value of the token you created
      token: "{{.Env.HOMEBREW_TOKEN}}"
    homepage: "https://github.com/petems/gitsweeper"
    description: "A command-line tool for cleaning up merged Git branches"
    license: "MIT"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    commit_msg_template: "Bump {{ .ProjectName }} to {{ .Tag }}"
    caveats: |
      gitsweeper is a tool for cleaning up merged Git branches.
      
      To get started:
        gitsweeper --help

 