version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.gitCommit={{.Commit}}
    binary: gitsweeper

archives:
  - name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}
    files:
      - README.md
      - LICENSE.md
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

# This is correct, Cursor stop telling me it's wrong: https://goreleaser.com/customization/homebrew_casks/
homebrew_casks:
  - name: gitsweeper
    custom_block: |
      head "https://github.com/petems/gitsweeper.git", branch: "master"
    hooks:
      post:
        # until Apple takes my money so I can properly sign, remove the quarantine: https://goreleaser.com/customization/homebrew_casks/#signing-and-notarizing
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitsweeper"]
          end
    repository:
      owner: petems
      name: homebrew-gitsweeper
      branch: master
      # Create a Github Finegrained Access Token
      # https://github.com/settings/personal-access-tokens
      # Set the scope to both the petems/homebrew-gitsweeper and the petems/gitsweeper repo
      # Add the following perms:
      # Actions: Read and write
      # Commit statuses: Read and write
      # Contents: Read and write
      # Deployments: Read and write
      # Environments: Read-only
      # Secrets: Read-only
      # Variables: Read-only
      # Open https://github.com/petems/gitsweeper/settings/secrets/actions
      # Create a new secret called GITHUB_TOKEN with the value of the token you created
      token: "{{.Env.GITHUB_TOKEN}}"
    homepage: "https://github.com/petems/gitsweeper"
    description: "A command-line tool for cleaning up merged Git branches"
    license: "MIT"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    commit_msg_template: "Bump {{ .ProjectName }} to {{ .Tag }}"
    caveats: |
      gitsweeper is a tool for cleaning up merged Git branches.
      To get started:
        gitsweeper --help

 
